packages:
  - "apps/*"
  - "packages/*"
overrides:
  "zod@^4.0.0": 4.6.5
allowBuilds:
  '@hugeicons/svelte': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
onlyBuiltDependencies:
  - esbuild
